- build.gradle
- build.sh
- docker/docker-compose.yml
- docker/sql/0002_gaia_source.sql
- docker/uws-sql/000_uws_create_schema.sql
- docker/uws-sql/001_uws_job_example.postgresl.sql
- docker/uws-sql/002_uws_job_detail_example_postgresql.sql
- docker/uws-sql/003_uws_job_availability.sql
- docker/vo2oracle/requirements.txt
- docker/vo2oracle/vo2oracle.py
- src/main/java/org/opencadc/tap/impl/ResultStoreImpl.java
- src/main/java/org/opencadc/tap/ws/QueryJobManager.java
- src/main/webapp/META-INF/context.xml
Merging demo tap service back to master to make it easier for people to find.
> [DM-15868] Merging demo back to master

- src/main/java/org/opencadc/tap/impl/QServBox.java
- src/main/java/org/opencadc/tap/impl/QServCircle.java
- src/main/java/org/opencadc/tap/impl/QServParsingHelpers.java
- src/main/java/org/opencadc/tap/impl/QServPoint.java
- src/main/java/org/opencadc/tap/impl/QServPolygon.java
- src/main/java/org/opencadc/tap/impl/QServRegion.java
- src/main/java/org/opencadc/tap/impl/QServRegionConverter.java
Still a ways to go with testing and such, but just wanting to get this to master to deploy it officially to start getting feedback.
This adds support for CONTAINS(point, circle) CONTAINS(point, box) CONTAINS(point, polygon) by rewriting the query and adding the appropriate scisql functions.
> [DM-17187] Initial ADQL rewriting

- .gitignore
- build.sh
- docker/Dockerfile.querymonkey
- integration_test/querymonkey/querymonkey.py
- integration_test/querymonkey/requirements.txt
- integration_test/querymonkey/run.sh
- integration_test/querymonkey/test_queries/box.sql
- integration_test/querymonkey/test_queries/circle.sql
- integration_test/querymonkey/test_queries/polygon.sql
- kube/create_secret.sh
- kube/querymonkey-deployment.yaml
- push.sh
Make a service that runs semi random queries, and posts failures to slack.
> [DM-17380] Add continuous monitoring of TAP service

- .travis.yml
- docker/checkAvailability.sh
- docker/docker-compose.yml
- docker/waitForContainersReady.sh
Fix issues like auth username in the travis job (so we can download from Oracle's maven repository), as well as fixing the docker-compose script, and adding a retry to some of the tests.
> [DM-17030] Get Travis working

- integration_test/querymonkey/querymonkey.py
- integration_test/querymonkey/test_queries/neighbor_count.sql
- integration_test/querymonkey/test_queries/neighbor_far.sql
- integration_test/querymonkey/test_queries/neighbor_near.sql
We've been having some timeouts, which add noise into the monitoring.
With the help of the team, make some better queries with better
entropy limits.
> [DM-19688] Modify neighbor queries for monkey

- kube/int/auth-ingress.yaml
- kube/int/auth_off.sh
- kube/int/auth_on.sh
Also some helper scripts to help turn it on and off.
> [DM-19834] Add auth-ingress rule

- kube/int/auth_off.sh
- kube/int/auth_on.sh
- kube/int/create.sh
- kube/int/create_secret.sh
- kube/int/destroy.sh
- kube/stable/create.sh
- kube/stable/create_secret.sh
- kube/stable/destroy.sh
- kube/stable/monitor.sh
Related to the splitting of the kubernetes clusters at NCSA.
> [DM-19835] k8s namespace changes

- src/main/webapp/capabilities.xml
We need all the urls here to be correct and represent the https
endpoint, so the auth will work.
> [DM-20131] Update capabilties for https

- src/main/java/org/opencadc/tap/ws/TAPWebService.java
Small change in the interface so we need to provide an implementation
for this method.  I'm using the same comment that was added from
the example TAP server.
> [DM-20425] Fix upstream break

- kube/int/auth-ingress.yaml
- kube/int/tap-ingress.yaml
- kube/stable/tap-ingress.yaml
Rewrite rules have to be updated to work with the new ingress
format for rewrite-rules.
> [DM-20372] Update ingress rules for new ingress controller.

- build.gradle
- kube/int/tap-deployment.yaml
- src/main/java/org/opencadc/tap/impl/AuthenticatorImpl.java
- src/main/java/org/opencadc/tap/ws/QueryJobManager.java
In the AuthenticatorImpl class, which we tie in using a system
property passed in at runtime to point to our class.  This class
will look for a BearerTokenPrincipal and then decode it into
other principals with the user id and name to use in other
parts of the code.
We decode the token using a 3rd party library that handles these
sorts of things.
> [DM-20729] Parse Bearer Token

- docker/docker-compose.yml
- docker/tap-schema/0000_tap_schema11.sql
- src/main/webapp/WEB-INF/web.xml
Fix the availability endpoint and the travis job, which checks this and runs a sync query to make sure that the tap_schema parts are working.
There were actually some interesting upstream changes that needed to be taken into account in our code, which are now hopefully all fixed.
> [DM-21826] Fix availability and travis

- .travis.yml
- src/main/java/org/opencadc/tap/impl/ResultStoreImpl.java
- test.sh
Allow configuration options to set which google bucket to use and what URL to point
people at.
> [DM-22649] Make async bucket configurable

- src/main/java/org/opencadc/tap/impl/AuthenticatorImpl.java
This interface changed so fix the build break.
> [DM-30705] Fix authentication interface

- src/main/java/org/opencadc/tap/impl/AuthenticatorImpl.java
We're seeing GOAWAY IOException errors from the HTTP request to
Gafaelfawr that correspond to a 499 error on the NGINX side.  See
if a simple retry loop around the request will fix this problem.
Try five times before throwing the exception.
> [DM-30906] Add retry loop for Gafaelfawr request

- src/main/java/org/opencadc/tap/impl/AuthenticatorImpl.java
This will allow us to make fewer requests to gafaelfawr.
We just need to be able to look up the uid number and the
email address based on token.  Since the same token will
be used for quite a while, it's a good idea to cache that.
> [DM-30958] Cache gafaelfawr user-info requests

- src/main/java/org/opencadc/tap/ws/TAPWebService.java
Availability break made our build ironically unavailable.
> [DM-34891] Get build working again

- dev-values.yaml
- src/main/resources/log4j.xml
Add a log4j xml and let's see.  Also fix up dev-values to be current.
> [DM-35242] Try to get log4j to work again

- src/main/webapp/WEB-INF/web.xml
This is so we can hopefully get more information about the IncompleteRead errors coming from mobu.
> [DM-37254] Turn on debug level debugging

- src/main/webapp/WEB-INF/web.xml
> Turn down debug logs to info

- src/main/webapp/capabilities.xml
Other edits, mainly to the ADQL capabilities, will have to come later after more contact with @fritzm et al.
> DM-37934: Remove claims of UPLOAD capabilities not supported in Qserv

- build.gradle
This contains the PR that has the math typing
extras.
> [DM-17872] Bump dependency cadc-adl to 1.1.13

- src/main/java/org/opencadc/tap/impl/RubinUploadManagerImpl.java
- Add convertVOTableTypeToMySQL that converts the upload types to the MySQL equivalent
- Properly handle arraysizes in uploaded fields
> DM-51713: Fix upload field type conversion

- src/main/java/org/opencadc/tap/impl/RubinUploadManagerImpl.java
- src/main/java/org/opencadc/tap/kafka/util/DatabaseNameUtil.java
- src/main/java/org/opencadc/tap/kafka/util/KafkaJobService.java
Add unique UWS job id to name of user upload database
Encapsulate database name generating code into one class
> DM-51809: Create new database for each upload job
