lsst-sqre/lsst-tap-service

- kube/tap-deployment.yaml
- src/main/java/org/opencadc/tap/impl/AdqlQueryImpl.java
- src/main/java/org/opencadc/tap/impl/QServRegionConverter.java
- src/main/java/org/opencadc/tap/schema/ALMATapSchemaDAO.java
- src/main/webapp/capabilities.xml
This allows for all the normal qserv_areaspec_* and scisql functions to be called through the TAP service.  In this, we get rid of Presto from the mix (because it doesn't pass down UDFs), whitelist the UDF names, and additionally wire up the ADQL parser (although there's no implementation yet).
> [DM-17021] Allow qserv_ functions to be called through TAP

- src/main/java/org/opencadc/tap/ws/TAPWebService.java
- src/main/webapp/META-INF/context.xml
The availability endpoint was giving a SQL exception running
the query against TAP_SCHEMA.  This is because this goes through
a different call path that doesn't lowercase all the table names,
and mysql is sadly case sensitive as to table names.  So make
the table names lowercase, and get rid of some of the additional
ALMA checking.
Also get rid of some trailing whitespace in the context.xml file.
With this, the availability endpoint says everything is well.
> [DM-17455] Fix availability endpoint.

- docker/tap-schema/0005_tap_schema_self11.sql
- docker/tap-schema/1000_table_create.sql
- docker/tap-schema/1002_gaia_source.sql
- docker/tap-schema/1003_uws_tap_schema.sql
Order UWS, Gaia, and tap_schema lower than SDSS and wise.
For some reason, TOPCAT doesn't seem to respect the schema
index ordering.  But the schema index is set.
> [DM-18451] Update schema_index for schemas.

- integration_test/querymonkey/test_queries/count.sql
- integration_test/querymonkey/test_queries/neighbor.sql
COUNT(*) will hit all the workers, so by adding this query into the
mix we can verify all the workers are available and servicing queries
when this gets run.
> [DM-19340] Add count query to monkey queries

- kube/stable/querymonkey-deployment.yaml
Such a smart monkey.  Let's use the internal service
IP to connect.  While I'm a bit worried that this won't test
out the ingress parts, honestly that has to be part of it,
since there's no automated way to get a token for a service.
> [DM-21880] Have the query monkey work around auth

- src/main/java/org/opencadc/tap/schema/ALMATapSchemaDAO.java
This will allow the TAP service to know how to parse these functions
and what types they return, which is needed to transform these things
into a VOTable.
> [DM-21176] Add remaining scisql functions to TAP's list

- docker/docker-compose.yml
- src/main/webapp/WEB-INF/web.xml
First off, get rid of that group thing.  We don't have that group.
Then, set up the new PropertyReaders.dir to point to /etc/creds, where the secrets are placed.  If the file doesn't exist, that's fine.  Then point it at the file in the directory in web.xml (PropertyReader will look in the directory set in the system property).
> [DM-22959] Allow configuration of who can fiddle log setting

- integration_test/querymonkey/test_queries/circle.sql
- integration_test/querymonkey/test_queries/count.sql
- integration_test/querymonkey/test_queries/neighbor_count.sql
- integration_test/querymonkey/test_queries/neighbor_far.sql
- integration_test/querymonkey/test_queries/neighbor_near.sql
- integration_test/querymonkey/test_queries/polygon.sql
Minor updates:
* no SDSS data in small qserv; use wise_01 instead
* update ra/dec column names as appropriate
* update for new numeric Wise PKs
> Update querymonkey templates for datasets in small qserv instance

- .github/workflows/reap.yaml
The async reaper action is failing because it can't install the
dependencies of google-cloud-storage.  Assume that this is because
ubuntu:latest comes with too old of a version of Python and try
installing Python 3.10 first to see if that fixes the problem.
> Use Python 3.10 for async reaper

- docker/Dockerfile.lsst-tap-service
Apparently the new build of the same base container doesn't have
unzip by default.
> [DM-35704] Try to add unzip back

- docker/Dockerfile.lsst-tap-service
**Description:**
Include the installation of unzip in the TAP Dockerfile
**Issue:**
When attempting to run a recent build & deploy of the TAP service, the deployment failed with an error message 
> unzip: command not found
If the above description is correct, and judging from the symptoms, it seems that unzip is not installed by default in the tomcat:9:0 image. I have tried running a bare tomcat:9 docker run and can confirm that "unzip" is not available.
**Date when issue first spotted:**
2022/06/30
**Link to issue description:**
https://issuehint.com/issue/docker-library/tomcat/267
**Environment:**
Minikube version: v1.25.1
**Version tested:**
Latest (6c5cfae054b691214a0185fba4a8299c57dea33b)
**Fix:**
Include an apt-get install of unzip in the TAP Dockerfile
> Added unzip installation to TAP Dockerfile

- src/main/java/org/opencadc/tap/impl/ResultStoreImpl.java
This resolves a problem with bucket names containing ":" that can otherwise be interpreted as a URL scheme instead of a path component.
Note that this prevents the `bucketURL` endpoint from having a path component, but this is not a problem for any known S3 service.
> DM-38493: Make S3 bucket paths absolute.

- src/main/webapp/capabilities.xml
Following consultation with @ktlim and @iagaponenko (who might not be able to see this repo?) I'm removing statements from the Qserv-based TAP service's `/capabilities` response for ADQL constructs that are not currently supported in Qserv: `REGION`, `INTERSECTS`, `AREA`, `CENTROID`, `COORD1`, and `COORD2`.
Compared to the recent fix re: `UPLOAD`, this is less urgent, because Firefly does not (yet) condition its behavior on these features.
> DM-37934: Remove advertisements for ADQL geometry entities not supported by Qserv

- src/main/java/org/opencadc/tap/impl/QServQueryRunner.java
Right now this is printed out at the debug level, but it will be a lot easier to find and get a hold of if we make it a warning.  Since this is an exception path, this shouldn't really add too much log spam, considering the rethrown messages are emitted after, but we seem to lose the first one which is the most important.
> [DM-37254] Emit exception message as warning

- src/main/java/org/opencadc/tap/impl/QServQueryRunner.java
- src/main/java/org/opencadc/tap/impl/ResultStoreImpl.java
By setting auto commit to false, it should reduce the memory usage and seems to be one of the parts of making sure we use a cursor for the select statements.  If we don't use a cursor then the jdbc driver reads everything into memory before returning it.
> [DM-41951] setAutoCommit to false

- build.gradle
**Description:**
PR addresses issue where most recent version on main fails to build.
Build run locally using Gradle version 7.6 produces compilation errors:
```
/app/src/main/java/org/opencadc/tap/ws/TAPWebService.java:85: error: TAPWebService is not abstract and does not override abstract method getStatus() in AvailabilityPlugin
public class TAPWebService implements AvailabilityPlugin {
^
/app/src/main/java/org/opencadc/tap/ws/TAPWebService.java:119: error: getStatus() in TAPWebService cannot implement getStatus() in AvailabilityPlugin
public Availability getStatus() {
^
return type Availability is not compatible with AvailabilityStatus
/app/src/main/java/org/opencadc/tap/ws/TAPWebService.java:118: error: method does not override or implement a method from a supertype
@Override
``` …
> Changed target version for vosi, fixes issue with build

- CHANGELOG.md
- build.gradle
- changelog.d/_template.md.jinja
- changelog.d/scriv.ini
- docker/Dockerfile.lsst-tap-service
- docker/start.sh
- src/main/java/org/opencadc/tap/impl/AuthenticatorImpl.java
- src/main/java/org/opencadc/tap/impl/UWSInitAction.java
- src/main/webapp/META-INF/context.xml
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/capabilities.xml
**Description**
This PR addresses a few tasks / issues:
- Enable UWS Initialisation / Used for populating an empty UWS database, which will be useful now that we are switching UWS to CloudSQL
- Fix Capabilities (based on discussions with rra / following cadc / taplint validator)
- Adds scriv changelog documentation (Don't know if I got that quite right yet?)
- Tag Authenticator as deprecated. Functionality now part of the upstream cadc-tap code, via the IdentityManager class
- Switch to using cadc-tomcat base Docker image
- Bring cadc library versions up-to-date
**Related JIRA issues**
https://rubinobs.atlassian.net/browse/DM-44607
https://rubinobs.atlassian.net/browse/DM-44746
https://rubinobs.atlassian.net/browse/DM-44524
**How was this tested**
Tested on dev with custom DockerHub image …
> Update Cadc libraries / Enable UWS init action / Switch to tomcat image

- CHANGELOG.md
- build.gradle
**Jira issue description:**
> 
> The mysql-connector-java version in the lsst-tap-service appears to be 8.0.13, which dates from 2018 (and is listed as having three direct vulnerabilities, but which are not that severe: [CVE-2022-21363](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21363), [CVE-2021-2471](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-2471), [CVE-2019-2692](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-2692)).
> 
> We should try updating to at least 8.0.33 or possibly [mysql-connector-j](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j) 8.4.0, which appears to be the most recent available.
> 
> Among other things, this should enable us to use TLS 1.3, which is a recommended mitigation for having Qserv exposed to the Internet.
> …
> Upgrade mysql connector to 8.4.0

- CHANGELOG.md
- build.gradle
**Summary**
- Fixed issue where the stils starlink package causes conflicts with dali package with the same name, during TAP_UPLOAD with binary data
- Remove duplicate cadc-libs
**Tests**
_Taplint:_
Expected: Totals: Errors: 97; Warnings: 695; Infos: 158; Summaries: 20; Failures: 3 (on main version)
Actual: Totals: Errors: 97; Warnings: 695; Infos: 158; Summaries: 20; Failures: 3 (tickets/DM-45142)
Errors & warning match between the two (This should eventually be an automated test)
_Notebooks:_
DP02_02_Catalog_Queries_with_TAP (Sucess)
DC2_catalog_access (Sucess)
DP02_13a_Image_Cutout_SciDemo (Sucess)
_Firefly:_
Test DP02 tab with object: 62, -37 (Success)
Test D02 with query: SELECT TOP 10 * FROM dp02_dc2_catalogs.Object (Success)
TAP_UPLOAD Not tested (Not possible atm)
> Remove cadc lib not needed & fix starlink conflict

- CHANGELOG.md
- docker/Dockerfile.lsst-tap-service
- docker/start.sh
**Summary**
There was a bug in the changes made in the previous upgrade to using the cadc-tomcat base image, where the start script was not run correctly. This change modifes the Dockerfile to run our script as an ENTRYPOINT and have that call the underyling /usr/bin/cadc-tomcat-start script.
**Tests**
Tested on dev with the following usage scenarios:
- Run simple select top 10 sync/async queries
- Get some data from ivoa.Obscore and make sure datalinks show up correctly
- Run taplint:
`Totals: Errors: 97; Warnings: 695; Infos: 158; Summaries: 20; Failures: 3`
The errors & warning are all the expected ones, which should be fixed soon (metadata, missing tables & sync POST bug in topcat)
> Use our start script as ENTRYPOINT and have that call cadc start script

- CHANGELOG.md
- src/main/webapp/capabilities.xml
**Description**
We use the following authentication mechanism with pyvo:
```
s = requests.Session()
s.headers["Authorization"] = "Bearer " + token
auth = pyvo.auth.authsession.AuthSession()
auth.credentials.set("lsst-token", s)
tap_service = pyvo.dal.TAPService(baseurl=tap_url,
session=auth)
auth.credentials.set("lsst-token", s)
auth.add_security_method_for_url(tap_url, "lsst-token")
auth.add_security_method_for_url(tap_url + "/sync", "lsst-token")
auth.add_security_method_for_url(tap_url + "/async", "lsst-token")
auth.add_security_method_for_url(tap_url + "/tables", "lsst-token")
```
With the updated capabilities we switched to using "full" for as the accessURL use type, however this leads to pyvo not finding the "lsst-token" security method when we make a request to "/tables" because it …
> Change accessURL use for /tables to "base"

- CHANGELOG.md
- build.gradle
- src/main/java/org/opencadc/tap/impl/AuthenticatorImpl.java
- src/main/java/org/opencadc/tap/ws/QueryJobManager.java
**Summary**
Now that the previous Authenticator class and its implementation is deprecated in the new Cadc library, it's been replaced by the IdentityManager abc. During the switchover we started by using the StandardIdentityManager class found here:
https://github.com/opencadc/ac/blob/2d178c4291da715ce17fb3ed596169be204bc406/cadc-gms/src/main/java/org/opencadc/auth/StandardIdentityManager.java#L110
This seemed to work, however I've recently found a bug where the ownerID value of UWS jobs was empty. 
This PR introduces a new implementer of the Abstract IdentityManager class, which uses the methods defined in our previous AuthenticatorImpl.java class, and for the new abc methods I use the implementations found in the StandardIdentityManager class.
This seems to work now, as authentication …
> [DM-45303] Change authentication provider in QueryJobManager & fix issue with ownerID missing from uws

- CHANGELOG.md
- src/main/resources/log4j.xml
- src/main/webapp/WEB-INF/web.xml
Current setup produces a few warnings from the logging servlet, where it complains about a missing header in log4j.xml and a warning about a log message which should not be appearing. The second one is fixed by remove ca.nrc.cadc.log from the logLevelPackages in the web.xml configuration. A Doctype is added to address the first issue.
> Remove cadc-tap log package from logLevelPackages & Add header to log4j.xml

- CHANGELOG.md
- src/main/webapp/META-INF/context.xml
**Summary**
There is an issue on prod where TAP does not execute any async queries, which end up being stuck in a "QUEUED" state.
**Version of TAP**
2.3.1
**More details**
https://rubinobs.atlassian.net/browse/DM-45307
**Proposed fix**
Revert  UWS connection pool setting back to what they were pre 2.3.1
**Date observed**
- July 17 2024
- July 12 2024
> Revert uws connection pool settings to release 2.3.0

- build.gradle
- changelog.d/20240813_174428_steliosvoutsinas_DM_45739.md
**Summary:**
- Remove jcenter repo as it is obsolete and no longer used by cadc
- Remove org.restlet.jee:org.restlet.ext.servlet:2.0.3 no longer needed
> DM-45739: Remove restlet and obsolete maven repos

- build.gradle
- changelog.d/20241125_182819_steliosvoutsinas_DM_47788.md
- docker/Dockerfile.lsst-tap-service
Bump version of cadc-gms to >=1.0.14 which uses the new OIDC discovery mechanism (looks for .well-known endpoint).
This requires an update to phalanx to set OIDC issuer to the base url of the RSP.
> Update version of gms to 1.0.14 and fix Dockerfile warning about LABEL

- build.gradle
- changelog.d/20250114_162646_steliosvoutsinas_DM_48132.md
- src/main/java/org/opencadc/tap/impl/MaxRecValidatorImpl.java
- src/main/java/org/opencadc/tap/impl/QServQueryRunner.java
- src/main/java/org/opencadc/tap/impl/ResultSetWriter.java
- src/main/java/org/opencadc/tap/impl/RubinFormatFactory.java
- src/main/java/org/opencadc/tap/impl/RubinTableWriter.java
Introduce a Binary2 VOTable serialization to the RSP TAP services, enabled by default instead of TableData. Maintain the ability to request TableData format explicitly which works by specifying the format in the TAP request. 
This change improves performance by using a more efficient serialization format.
- Added support for distinguishing between VOTABLE (Binary2) and VOTABLE-TD formats
- Updated format initialization to handle VOTABLE-TD format separately
- Updated row count tracking to properly handle all formats
- Implements table writing for Binary2 VOTable format
- Supports proper handling of table metadata including:
- Column information preservation
- URL rewriting for ObsCore access_url fields
- Row count tracking
- Overflow detection
- Handles maxrec limits correctly
- Verified …
> DM-48132: Introduce Binary2 VOTable Serialization and make it default

- build.gradle
- changelog.d/20250212_150652_steliosvoutsinas_DM_48908.md
- src/main/java/org/opencadc/tap/impl/ALMATableServlet.java
- src/main/java/org/opencadc/tap/impl/AdqlQueryImpl.java
- src/main/java/org/opencadc/tap/impl/CapGetAction.java
- src/main/java/org/opencadc/tap/impl/CapInitAction.java
- src/main/java/org/opencadc/tap/impl/MaxRecValidatorImpl.java
- src/main/java/org/opencadc/tap/impl/QServCircle.java
- src/main/java/org/opencadc/tap/impl/QServPoint.java
- src/main/java/org/opencadc/tap/impl/QServPolygon.java
- src/main/java/org/opencadc/tap/impl/QServRegion.java
- src/main/java/org/opencadc/tap/impl/QServRegionColumn.java
- src/main/java/org/opencadc/tap/impl/QServRegionConverter.java
- src/main/java/org/opencadc/tap/impl/ResultSetWriter.java
- src/main/java/org/opencadc/tap/impl/RubinTableWriter.java
- src/main/java/org/opencadc/tap/schema/ALMATapSchemaDAO.java
In most recent changes to the cadc-dali package, they changes some of the method signatures for the TableWriter classes.
This broke our builds, so this PR addresses this by removing and adjusting some of our methods to work with the upstream interfaces.
> DM-48908: Fix Rubin Table writes to work with newer version of cadc-dali

- changelog.d/20250219_144107_steliosvoutsinas_DM_49026.md
- src/main/java/org/opencadc/tap/impl/RubinRegistryServlet.java
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/resource-caps
We recently noticed an issue where all TAP services were misbehaving with what turned out to be a broken web service at cadc: https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/resource-caps. This gets queried by the RegistryClient class in the reg package of cadc, which occurs when /capabilities is checked. In this case this request was timing out due to an outage at CADC.
To address this we introduce a new '/reg' endpoint which is can be queried and returns an empty file for the '/reg/resource-caps' endpoint which is what is queried by the RegistryClient to collect additional metadata for capabilities. This does not have to contain any content in our case as our capabilities endpoints don't depend on any extra resource-caps.
> DM-49026: Add new /reg endpoint to remove dependency on external cadc web-service

- build.gradle
- build.sh
- changelog.d/20250226_121600_steliosvoutsinas_DM_49187.md
- Upgrade to JRE 11
- Update to cadc-adql 1.1.14
- Remove copying in patch of cadc-adql 1.1.13 since the changes have been merged in
> DM-49187: Upgrade to JRE 11 and set cadc-adql requirement to 1.1.14 and above

- build.gradle
- changelog.d/20250308_033317_steliosvoutsinas_DM_49350.md
- src/main/java/ca/nrc/cadc/reg/client/CachingFile.java
- src/main/java/ca/nrc/cadc/uws/server/JobDAO.java
- src/main/java/org/opencadc/tap/impl/QServQueryRunner.java
- src/main/resources/log4j.xml
- src/main/resources/log4j2.xml
- src/main/webapp/WEB-INF/web.xml
- Enable log4j, needed by cadc-log package
- Keep log4j2 for Sentry
- Remove checkpoints from JobDAO class
- Explicitly capture Sentry exception
> DM-49350: Re-enable log4j configuration for cadc-log, keep log4j2 for sentry

- src/main/webapp/META-INF/context.xml
- src/main/webapp/WEB-INF/web.xml
The TableServlet class from the vosi package is now being replaced in the ustream repos. Instead we now use RestServlet, however this requires setting up a jdbc/tapadm resource in the context so in this PR we add this as well.
> DM-49777: Change TableServlet to use RestServlet with a jdbc/tapadm resource

- src/main/java/org/opencadc/tap/impl/RubinUploadManagerImpl.java
- src/main/resources/log4j2.xml
- src/main/webapp/capabilities.xml
- Fixes issue with binary2 uploaded table appearing empty, by removing deprecated rowlimit-based upload constructor
- Also fixes logging issue, by removing Sentry logging for now 
- Update capabilities to show proper file size limit
Addresses JIRA issues:
- https://rubinobs.atlassian.net/browse/DM-51463
- https://rubinobs.atlassian.net/browse/DM-51458
> DM-51463: Fix issue with binary2 uploaded table appearing empty

- src/main/java/org/opencadc/tap/kafka/util/VOTableUtil.java
Simply add UnicodeChar as an available type in `convertTapDataTypeToVOTableType` in the VOTableUtil class so that we can handle unicodeChar as an uploaded table field.
> DM-51834: Add support for unicodeChar for uploaded tables

- src/main/java/org/opencadc/tap/impl/uws/server/KafkaJobExecutor.java
- src/main/java/org/opencadc/tap/kafka/services/JobStatusListener.java
- src/main/java/org/opencadc/tap/kafka/util/KafkaJobService.java
- src/main/webapp/capabilities.xml
This PR fixes a few issues related to validation:
- Update capabilities to correctly advertise only the formats we currently support
- Allow aborting jobs that have not been started
- Write error messages we get in the Job Status updates as error VOTables to GCS.
Related JIRA issues:
- https://rubinobs.atlassian.net/browse/DM-52483
- https://rubinobs.atlassian.net/browse/DM-52479
- https://rubinobs.atlassian.net/browse/DM-52477
> DM-52477: Fix capabilities so that we only advertise votable/binary2 as the output format
